---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - service-account.yaml

images:
- name: image-name
  newName: ghcr.io/sibuthomasmathew/ci-tests
  newTag: web-app-5
