name: Build and Push

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

env:
  APP: web-app
  REGISTRY: ghcr.io
  IMAGE_NAME:  ${{ github.repository }}
  TRIVY_USERNAME: ${{ github.actor }}
  TRIVY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:

  build_docker_and_push_to_github_packages:
    name: Build and Push Docker image.
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.APP }},suffix=-${{ github.run_number }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile
          platforms: linux/amd64

      - name: Run Trivy vulnerability scanner in image mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: '${{ steps.meta.outputs.tags }}'
          scan-type: 'image'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
